# based on https://github.com/marketplace/actions/build-and-push-docker-images

name: Build Docker Image
on:
  push:
    branches: [ "main" ]
    paths:
      - Dockerfile
  pull_request:
    branches: [ "main" ]
    paths:
      - Dockerfile
  workflow_dispatch:
 
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: deanvry/netutils

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GIHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
